version: 2
updates:

  # Watch for any Go dependency updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep our version of Go up to date in the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update GitHub Actions we're using
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
